default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: library_management_system_development

test:
  <<: *default
  database: library_management_system_test

production:
  <<: *default
  database: library_management_system_production
  username: library_management_system
  password: <%= ENV['LIBRARY_MANAGEMENT_SYSTEM_DATABASE_PASSWORD'] %>
